types = ['american', 'arabic', 'chinese', 'greek', 'indian', 'italian', 'japanese', 'lebanese',
         'mexican', 'argentinean', 'romanian', 'serbian', 'turkish', 'vegetarian']

restaurant_data = [['american', 'Oro Toro', '3', '3', 'Street Aristide Demetriade, no. 1.'],
                   ['american', 'Ribs Grill','4', '5', 'Calea Sagului, no. 100.'],
                   ['american', 'Meat Busters', '2', '1', 'Street Gheorghe Lazar, no. 1'],
                   ['american', 'Eat Like a Man', '5', '4', 'Piata Unirii, no. 4.'],
                   ['arabic', 'Restaurant ZHH Termal', '3', '2', 'Bulevardul Vasile Parvan, no. 9.'],
                   ['arabic', 'Restaurant Miral', '4', '3', 'Strada Maresal Constantin Prezan, no. 146.'],
                   ['chinese', 'Marele Restaurant Chinezesc', '3', '2', 'Street Simion Barnutiu, no. 22.'],
                   ['chinese', 'Restaurant Marele Zid Chinezesc', '1', '4', 'Street Vasile Alecsandri, no. 2.'],
                   ['chinese', 'Chang Cheng', '3', '5', 'Street Aristide Demetriade, no. 1.'],
                   ['chinese', 'Fat Mao', '2', '4', 'Street Bucovinei, no. 49.'],
                   ['greek', 'Kos Greek Taverna', '4', '2', 'Street Gheorghe Lazar, no. 8.'],
                   ['greek', 'Cancun', '3', '3', '2030 Maple Rd.'],
                   ['indian', 'Restaurantul Radha Cuisine', '4', '5', 'Street Emanoil Ungureanu, no. 13.'],
                   ['italian', 'Daily', '2', '1', 'Street Aristide Demetriade, no. 1.'],
                   ['italian', 'Pizzeria Thalia', '5', '4', 'Bulevardul Sudului, no. 10-14.'],
                   ['italian', 'Restaurant Intermezzo', '3', '2', 'Piata Unirii, no. 3.'],
                   ['italian', 'Restaurant Casa Antinori', '4', '3', 'Calea Aradului, no. 14 A.'],
                   ['japanese', 'Restaurant Sushi Ya', '3', '2', 'Street Lucian Blaga, no. 14.'],
                   ['japanese', 'Wasabi Sushi Bar', '1', '4', 'Street Aristide Demetriade, no. 1.'],
                   ['lebanese', 'Falafel King', '3', '5', 'Street Aristide Demetriade, no. 1.'],
                   ['lebanese', 'Restaurant Fenice Palas', '2', '4', 'Street Aristide Demetriade, no. 1.'],
                   ['mexican', "Restaurant Harold's", '4', '2', 'Aleea Studentilor, no. 17.'],
                   ['mexican', 'Tik Tasty', '3', '3', 'Street Coriolan Brediceanu, no. 10 A.'],
                   ['argentinean', 'Restaurant Argentinian Steakhouse', '4', '5', 'Street Suceava, no. 10.'],
                   ['romanian', 'Restaurant La Fabrica', '2', '1', 'Street Stefan Cel Mare, no. 28.'],
                   ['romanian', 'Restaurantul Timisoreana', '5', '4', 'Piata Victoriei, no. 2.'],
                   ['romanian', '3F', '3', '2', 'Street Aristide Demetriade, no. 1.'],
                   ['romanian', 'Restaurant La Renaissance', '4', '3', 'Street Lacului, no. 1.'],
                   ['romanian', 'Beraria 700', '3', '2', 'Street Coriolan Brediceanu.'],
                   ['serbian', 'Restaurant Karadorde', '1', '4', 'Street Gheorghe Lazar, no. 2.'],
                   ['serbian', 'Grill Sarbesc', '3', '5', 'Piata Unirii, no. 4.'],
                   ['vegetarian', 'Brunch', '2', '4', 'Bulevardul Mihai Viteazu, no. 28.'],
                   ['turkish', 'Antalya', '4', '2', 'Calea Sagului, no. 22.'],
                   ['vegetarian', 'GreenAware', '1', '5', 'Bulevardul 16 Decembrie 1989, no. 54.'],
                   ['vegetarian', 'Onebite', '4', '5', 'Street Renasterii, no. 29.']]
